[phases.setup]
cmds = [
    "echo 'Setting NODE_ENV=production'",
    "export NODE_ENV=production"
]

[phases.install]
cmds = ["npm install --prefer-offline --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"